### ISSUE TITLE
Dual Delay improvements :)

### ISSUE THREAD

**Issue by NRG70** [Phal-anx/MSM#12]
Hi Michael!
Thanks for adding the request for buffer-clear buttons.
Could you please make it so that it is visible when they are being triggered? (go red from grey).

2nd request
Could you please make it so that the TIME rotary knobs show the corresponding value as long as they are held by the mouse knob while rotating.
Cause when they are being modulated it is hard to know what value they are at when setting them.

Thanks again for this fantastic delay unit.
Latif

**Comment by Phal-anx** [comment]
Sure I can add a lights or even make the button change color when triggered.. gonna think about how it looks best.
Gonna have a look at your 2nd request as well.

**Comment by NRG70** [comment]
Awesome, thanks Michael! :)
