### ISSUE TITLE
Dual Delay

### ISSUE THREAD

**Issue by NRG70** [Phal-anx/MSM#13]
request:

Hi :)
intrigued by this post:
https://www.facebook.com/groups/vcvrack/permalink/321204118539739/

i experimented a little bit with sending signals that normally would go to an 1v/oct input, into the time cv inputs of the delay unit.
to my surprise i got some interesting sonic results :) specially when modulating the feedback hehehe

Do you think you could implement this into the unit the correct way?
Say like a tiny toggle switch that switch between: time & v/oct

If this makes any sense at all :) 
if it doesn't make any sense just let me know as well :D

**Comment by Phal-anx** [comment]
I can have a look ;) when I m back on track again.. took some time off because I lost a family member 2 weeks ago.. but I will definitely check that out and let you know ;)

**Comment by NRG70** [comment]
yes i understand Michael! 
i noticed your post in FB. 
Thanks take your time! :)
