### ISSUE TITLE
Any chance of your modules being updated to v1?

### ISSUE THREAD

**Issue by pgatt** [Phal-anx/MSM#14]
Hi there Michael,

I was wondering if your modules would be released for v1 of Rack - there were some gems in there it would be a shame to lose.

Thanks,
Paul.

**Comment by themib777** [comment]
I came here to post the same request.  I currently keep a laptop with an older version of VCV just to be able to use your modules, this is turning out to be a bit of an issue for an upcoming performance as well.  Really love your modules, please consider investing the time to make them compatible with the new version of VCV.  I'm sure you would make a lot of people very happy. :)

**Comment by diimdeep** [comment]
Hello, any news ?

**Comment by Phal-anx** [comment]
I decided to make MSM open source again, so you guys can fork/port it to v1... it took me a very long time to give up on the project as I dont have time to work on it.. but this way it can get back into rack.. the only exception is the TVCF module.. I m not able to make it open source without breaking an agreement with Rob (the original creator of the Twin Peak filter)..

**Comment by netboy3** [comment]
I would love to take a stab at porting it to v1. I know that a lot of VCV folks are missing it and would be really excited in it showing up again in the Rack. Would you kindly be able to guide me to the location of the repo?

**Comment by pgatt** [comment]
I believe it’s this repo under the 0.6.52 branch.

**Comment by netboy3** [comment]
Oh! my bad. I just notice you've got a 0.6 branch in addition to the empty master. Thanks again for opening this up.

**Comment by Eurikon** [comment]
Thanks again Michael for opening this up to the community. 
So stoked on having this plugin back in Rack!

**Comment by pgatt** [comment]
Thanks for opening it up, look forward to using them again!

**Comment by themib777** [comment]
Thanks a lot for opening it up, @Phal-anx !

Crossing my fingers that these modules will be ported to V1 in the foreseeable future. :)

**Comment by netboy3** [comment]
@Phal-anx, thank you again for open-sourcing this wonderful classic set of modules. I have been working very hard for the past few days to get the modules fully ported to V1 and am on the final stretch (will probably be completed over the weekend). With that in mind I do have a few questions regarding the future of this plugin:

- Are you planning to continue maintaining this GitHub repo? If you are, then all updates will need to go through you as pull-requests and be communicated to the Rack library team by you. If you don't have time for this, I'll be happy to "adopt" the plugin (term coined by Andrew) and continue the work on a fork, including using the fork as the authoritative source for the plugin manager.

- Are you planning to keep maintaining the https://phal-anx.github.io/modules.html site? If not, it would probably be best to point the plugin metadata to it's GitHub README.md (obviously a new one) like most plugins do.

- Are you interested in having the author web page / author email address metadata pointing somewhere?

Obviously, all original authorship rights are and will be reserved to you.

**Comment by Phal-anx** [comment]
@netboy3, great that you decided to pick it up and port it to v1! As time is a big issue for me since a few months I would like it very much if you adopt it. I wont continue to maintain the repo..

Keep in mind that 1 module (TVCF) is missing in the code.. I can’t share it because of the agreement I have with Rob Hordijk
(original creator of the twinpeak filter). <- just in case someone asks you about it. 

The github.io page/repository is already gone.. I do have a backup of it so I can share it aswell if needed/wanted. Btw I designed to manual with OpenOffice.. I can send you the file directly or upload it here.

**Comment by netboy3** [comment]
@Phal-anx, thank you so much for your timely response. It would be great if you could share the manual (in OpenOffice version) here. It will save me time disassembling the current PDF. I also would like to know if you would like anything put as an "Author home page" or "Author Email Address" (The Phal-anx name will obviously be kept through).

**Comment by themib777** [comment]
This is excellent news, @netboy3 & @Phal-anx !  Thanks a lot for the effort you are putting in this at the moment, @netboy3.  This made my weekend... I will be so happy to be able to upgrade to V1 on my performance laptop.

**Comment by Phal-anx** [comment]
@netboy3 you will get the manual by tomorrow. It shouldn’t link in anyway to me anymore through the library etc.. otherwise i would most likely need to forward mails/support etc to you.. which doesn’t make sense. if you adopt it you are the current author.. i would change those things to whatever you want e.g. your mail address for support questions… just keep my license notice in the license.txt and don’t change the name (obviously) of the plugin

**Comment by Phal-anx** [comment]
If you want to point out somehow that I was the original creator of MSM I would appreciate it through mentioning it in the Manual..

**Comment by netboy3** [comment]
@Phal-anx, The author contact info is optional. If you don't mind, I would still like to mention "Phal-anx" (just that name) as the author. There would be no contact info that will be linked to it or you. I would be the current maintainer and folks would be able to contact me through the GitHub issue tracker, but you rightly deserve the title of author, both legally and ethically. Does that work for you?

**Comment by Eurikon** [comment]
Wonderful news here , oh my! 
Will be able to open some older patches and finish them :) 
Thanks @Phal-anx & @netboy3

**Comment by Phal-anx** [comment]
@netboy3 yea this will work.

**Comment by Phal-anx** [comment]
Here is the Manual:
[Manual.zip](https://github.com/Phal-anx/MSM/files/3800912/Manual.zip)

**Comment by netboy3** [comment]
Perfect. Thank you so much for your help!

**Comment by netboy3** [comment]
Just to make sure all the followers in this thread are aware. I've just released a pre-release of MSM 1.0.0RC1. You can find the forked updated repo at: https://github.com/netboy3/MSM-vcvrack-plugin and the binary builds are under the "releases" tab. In a few days (and if I don't hear of any major issues) I'll push it to the Plugin Manager.
