### ISSUE TITLE
Package does not clear the zip from the plugins folder

### ISSUE THREAD

**Issue by a1laserboy** [Phal-anx/MSM#7]
Hi,

I'm using Rack 0.5.1 on osx 10.12.6. I used the package manager to update your new update 0.5.4, and it results with the  a zip file left in the plugins folder.

According to Andrew Belts post on Facebook: That might mean the developers have given incorrect SHA256 hashes and need to update them

Thanks for your great modules :)

**Comment by Phal-anx** [comment]
I m already on it.. the incorrect SHA256 is not the case with my modules.. still trying to figure out what the actual problem is

**Comment by Phal-anx** [comment]
did a pull request with new SHA256 now aswell.. maybe it works now

thanks for your support
