### ISSUE TITLE
Linux binary fails to load on latest Rack 0.6 pull

### ISSUE THREAD

**Issue by davephillips** [Phal-anx/MSM#8]
Fedora 23 Linux
Rack master (0.6.x dev)

[warning] Failed to load library ./plugins/MSM/plugin.so: ./plugins/MSM/plugin.so: undefined symbol: _ZTIN4rack9ParameterE

VCV Rack commit 2465d44eafe037181c48b076c556eb636a754778
Author: Andrew Belt <andrewpbelt@gmail.com>
Date:   Sun Mar 18 10:06:14 2018 -0400

FWIW, I have the same error/issue with the current release of the Blamsoft binaries:

[warning] Failed to load library ./plugins/Blamsoft-XFXF35/plugin.so: ./plugins/Blamsoft-XFXF35/plugin.so: undefined symbol: _ZTIN4rack9ParameterE

Those binaries have been working up to the last couple of releases of Rack (within the past two days) and will require a rebuild. Hopefully the same is all that's needed for the MSM package.

**Comment by Phal-anx** [comment]
thanks for letting me know.. I gonna rebuild it with the latest version

**Comment by Phal-anx** [comment]
[MSM-0.6.0-lin.zip](https://github.com/Phal-anx/MSM/files/1827085/MSM-0.6.0-lin.zip)

@davephillips  please test this version. and let me know if you could load it.

**Comment by davephillips** [comment]
Hi Michael, thank you so much for the new package, everything loads fine in the latest Rack pull. I'll be testing them out over the next few days, I'll send a report soon. Thanks again, it's so nice to have the MSM plugins back on my system. :) Btw, they look terrific, you've done a great job on the graphics.

**Comment by Phal-anx** [comment]
Good to hear.. so I m replacing this one with the released one ;) 

yea let me know if you find any bug and overall feedback is welcome.
